extensions: with extensions; [
  extensions."30-seconds"."30-seconds-of-code"
  astro-build.astro-vscode
  bierner.comment-tagged-templates
  bierner.emojisense
  bierner.markdown-emoji
  bierner.markdown-mermaid
  bodil.blueprint-gtk
  bpruitt-goddard.mermaid-markdown-syntax-highlighting
  codespaces-contrib.codeswing
  davidanson.vscode-markdownlint
  drmerfy.overtype
  dtsvet.vscode-wasm
  ecmel.vscode-html-css
  editorconfig.editorconfig
  esbenp.prettier-vscode
  evaera.vscode-rojo
  firefox-devtools.vscode-firefox-debug
  fivethree.vscode-svelte-snippets
  github.github-vscode-theme
  github.remotehub
  hbenl.vscode-test-explorer
  icrawl.discord-vscode
  jnoortheen.nix-ide
  johnpapa.vscode-peacock
  kde.breeze
  koihik.vscode-lua-format
  levertion.mcjson
  marko-js.marko-vscode
  mhutchie.git-graph
  mikestead.dotenv
  ms-playwright.playwright
  ms-vscode-remote.remote-ssh
  ms-vscode-remote.remote-ssh-edit
  ms-vscode.hexeditor
  ms-vscode.live-server
  ms-vscode.remote-explorer
  ms-vscode.remote-repositories
  ms-vscode.test-adapter-converter
  ms-vsliveshare.vsliveshare
  mushan.vscode-paste-image
  nico-castell.linux-desktop-file
  nightrains.robloxlsp
  oven.bun-vscode
  piousdeer.adwaita-theme
  pkief.material-icon-theme
  redhat.vscode-commons
  redhat.vscode-xml
  redhat.vscode-yaml
  relm4.relm4-snippets
  roblox-ts.vscode-roblox-ts
  rust-lang.rust-analyzer
  scrimba.vsimba
  spgoding.datapack-language-server
  svelte.svelte-vscode
  swellaby.vscode-rust-test-adapter
  sysoev.language-stylus
  tamasfe.even-better-toml
  thenuprojectcontributors.vscode-nushell-lang
  thisismanta.stylus-supremacy
  ultram4rine.vscode-choosealicense
  unifiedjs.vscode-mdx
  usernamehw.errorlens
  vadimcn.vscode-lldb
  visualstudioexptteam.intellicode-api-usage-examples
  visualstudioexptteam.vscodeintellicode
  vivaxy.vscode-conventional-commits
  vscode-icons-team.vscode-icons
  yzhang.markdown-all-in-one
  ziglang.vscode-zig
]
